### ISSUE TITLE
MonadFix Q

### ISSUE THREAD

**Issue by phadej** [haskell-compat/th-compat#15]
Could we put in this (very lightweight package). `th-orphans` would be better named one, but it's quite big already (and uses `TemplateHaskell` extension, which is a bummer - i'd rather avoid that if I can).

**Comment by RyanGlScott** [comment]
I'd rather not do this, since I think this creeps the scope of the package into territory that I'm not comfortable with. I'm open to the idea of splitting up `th-orphans` into smaller packages, however. The parts of `th-orphans` that rely on `TemplateHaskell` can easily be separate from the parts than define orphan instances for `Q`.

**Comment by phadej** [comment]
I was mistaken, `MonadFix Q` is already in `th-orphans`. I guess one just have to live with that.
